plugins {
    id 'com.android.application'
    id 'org.jetbrains.kotlin.plugin.serialization'
}

group = 'com.example.endoapp'
version = '1.0-SNAPSHOT'

android {
    namespace 'com.example.endoapp'

    compileSdk 36

    defaultConfig {
        applicationId 'com.example.endoapp'
        minSdk 24
        targetSdk 36
        versionCode 1
        versionName '1.0'
    }
}

kotlin {
    jvmToolchain(21)
}

dependencies {
    testImplementation 'org.jetbrains.kotlin:kotlin-test'

    implementation 'androidx.appcompat:appcompat:1.8.0'

    implementation platform('io.github.jan-tennert.supabase:bom:3.8.0')

    implementation 'io.github.jan-tennert.supabase:postgrest-kt'
    implementation 'io.github.jan-tennert.supabase:auth-kt'

    implementation 'io.ktor:ktor-client-android:3.5.2'
}
